# Generated by Django 3.0 on 2024-03-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('logintype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('breed_name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('plant_type', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('district', models.CharField(default=0, max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('photo', models.CharField(max_length=300)),
                ('licence', models.CharField(max_length=300)),
                ('shop_type', models.CharField(max_length=30)),
                ('district', models.CharField(default=0, max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('ph_no', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=30)),
                ('PLANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='SHOP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop'),
        ),
        migrations.CreateModel(
            name='Pet_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=30)),
                ('PET', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='SHOP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop'),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=300)),
                ('idproof', models.CharField(max_length=300)),
                ('status', models.CharField(default='', max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('photo', models.CharField(max_length=300)),
                ('id_proof', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
    ]
