# Generated by Django 3.0 on 2024-03-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_stock',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plant_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=30)),
                ('PLANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=30)),
                ('PET', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pet')),
            ],
        ),
    ]
