# Generated by Django 3.0 on 2024-03-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240316_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet_cart',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='plant_cart',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='pet_stock',
            name='USER',
        ),
        migrations.AddField(
            model_name='pet_cart',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
