# Generated by Django 3.0 on 2024-03-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_payment_plant_ordermain_plant_ordersub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeliveryBoy')),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant_ordermain')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
