# Generated by Django 3.0 on 2024-03-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20240325_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLANT_ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant_ordermain')),
            ],
        ),
    ]
