# Generated by Django 3.0 on 2024-04-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20240401_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_ordermain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('ADDRESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeliveryAddress')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_ordersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30)),
                ('PLANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant')),
                ('PLANT_ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant_ordermain')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLANT_ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant_ordermain')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeliveryBoy')),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Plant_ordermain')),
            ],
        ),
    ]
