# Generated by Django 3.0 on 2024-04-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_assigned_order_payment_plant_ordermain_plant_ordersub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_stock',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
