# Generated by Django 3.0 on 2024-04-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_plantreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_ordermain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('ADDRESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeliveryAddress')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_ordersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30)),
                ('PET', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pet')),
                ('PET_ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pet_ordermain')),
            ],
        ),
    ]
