# Generated by Django 3.0 on 2024-04-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_petreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petreview',
        ),
    ]
