# Generated by Django 3.0 on 2024-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_petreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_ordermain',
            name='deldate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
