# Generated by Django 3.2.25 on 2024-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20240407_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='details',
            field=models.CharField(max_length=5000),
        ),
    ]
