# Generated by Django 3.2.25 on 2024-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_plant_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy',
            name='gender',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
